### ISSUE TITLE
[FEAT] css 수정 및 meta 태그 추가

### ISSUE THREAD

**Issue by leeseooo** [Team-Packman/Packman-Client#309]
### 기능 명세

- [x] 담당자 배정 모달 회색 이미지 삐져나오는 것 수정
- [x] 검색엔진에 노출될 정보 수정
- [x] 템플릿 선택하기 뷰 하단 button 수정
